# NOTE: this workflow is now running on Dronecode / PX4 AWS account.
# - If you want to keep the tests running in GitHub Actions you need to uncomment the "runs-on: ubuntu-latest" lines
#   and comment the "runs-on: [runs-on,runner=..." lines.
# - If you would like to duplicate this setup try setting up "RunsOn" on your own AWS account try https://runs-on.com

name: Setup Tools Test (Ubuntu)

on: push

jobs:
  ubuntu-run:
    strategy:
      fail-fast: false
      matrix:
        version: [22, 24]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    #runs-on: [runs-on,runner=8cpu-linux-x64,"image=ubuntu${{ matrix.version }}-full-x64","run-id=${{ github.run_id }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: ownership workaround
      #   run: git config --system --add safe.directory '*'

      - name: Install pre-requisites
        run: |
            git clone https://github.com/zeromq/cppzmq.git
            cd cppzmq
            mkdir build
            cd build
            cmake ..
            sudo make install
            cd ../..

      - name: Install Dependencies
        run: |
            sudo apt-get install -y libunwind-dev
            ./Tools/setup/ubuntu.sh

      - name: Make Default Build
        run: |
            make px4_sitl_default
